version: "3.9"

name: nextcloud

networks:
  nextcloudapp:
    driver: bridge

volumes:
  postgres:
  redis:

services:
  # mariadb:
  #   env_file:
  #     - mariadb.env
  #   restart: unless-stopped
  #   image: mariadb:latest
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   #healthcheck:
  #   #  test: ["CMD", "mysql $MYSQL_DATABASE -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1;'  || exit 1"]
  #   #  interval: 2s
  #   #  retries: 120
  #   ports:
  #     - :3306
  #   volumes:
  #     - ./data/mariadb:/var/lib/mysql
  #   networks:
  #     - nextcloudapp

  # phpmyadmin:
  #   env_file:
  #     - phpmyadmin.env
  #   restart: unless-stopped
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - :80
  #   networks:
  #     - nextcloudapp
  postgres:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - postgres.env
    ports:
      - 8045:5432
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      - nextcloudapp
    command: postgres -c max_connections=200

  redis:
    image: redis:alpine
    restart: unless-stopped
    env_file:
      - redis.env
    volumes:
      - redis:/data:rw
    networks:
      - nextcloudapp

  nextcloud:
    env_file:
      - postgres.env
      - redis.env
      - nextcloud.env
    restart: unless-stopped
    image: nextcloud:fpm-alpine
    depends_on:
      - postgres
      - redis
    #depends_on:
    #  mariadb:
    #    condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=1
    ports:
      - :9000
    volumes:
      - ./data/nextcloud:/var/www/html:rw
      - postgres:/var/lib/postgresql/data:rw
      # - ./data/mariadb:/var/lib/mysql
    volumes_from:
      - postgres
      - redis
    networks:
      - nextcloudapp

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - nextcloud
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:rw
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./config/certbot:/etc/nginx/certbot:ro
      - ./data/nextcloud:/var/www/html:ro
      - ./log/nginx:/var/log/nginx:rw
    volumes_from:
      - postgres
      - redis
      - nextcloud
    networks:
      - nextcloudapp

  certbot:
    restart: unless-stopped
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - postgres
      - redis
      - nextcloud
      - nginx
    networks:
      - nextcloudapp
